services:
  my-db:
    image: postgres:15-alpine
    restart: always
    container_name: newtask
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=newtask
